import type { Song } from './types';

// The user's Ultimate Guitar favorites, imported as song stubs (link only,
// no chords yet). Opening one lets you fetch or paste its chords. Generated
// from their exported favorites page. Order preserved as in the export.
//
// Tuple: [artist, title, tab path, type]. URL = UG_BASE + path.
const UG_BASE = 'https://tabs.ultimate-guitar.com/tab/';

type Row = [string, string, string, string];

const ROWS: Row[] = [
  ['John Prine', 'Clay Pigeons (ver 2)', 'john-prine/clay-pigeons-chords-1197098', 'chords'],
  ['Passenger', 'Let Her Go', 'passenger/let-her-go-chords-1137467', 'chords'],
  ['John Prine', 'Summers End', 'john-prine/summers-end-chords-2313799', 'chords'],
  ['Guy Clark', 'Magnolia Wind', 'guy-clark/magnolia-wind-chords-1238386', 'chords'],
  ['Bob Dylan', 'Make You Feel My Love (ver 3)', 'bob-dylan/make-you-feel-my-love-chords-1189445', 'chords'],
  ['Hank Williams', 'Im So Lonesome I Could Cry (ver 3)', 'hank-williams/im-so-lonesome-i-could-cry-chords-1117274', 'chords'],
  ['Simon & Garfunkel', 'The Boxer', 'simon-garfunkel/the-boxer-tabs-525097', 'tab'],
  ['Fleetwood Mac', 'Never Going Back Again', 'fleetwood-mac/never-going-back-again-tabs-43919', 'tab'],
  ['Donovan', 'Colours (ver 2)', 'donovan/colours-chords-1044082', 'chords'],
  ['Bruce Springsteen', 'If I Should Fall Behind', 'bruce-springsteen/if-i-should-fall-behind-chords-56412', 'chords'],
  ['Nirvana', 'Jesus Doesnt Want Me For A Sunbeam (ver 2)', 'nirvana/jesus-doesnt-want-me-for-a-sunbeam-chords-1106860', 'chords'],
  ['Tegan and Sara', 'When I Get Up', 'tegan-and-sara/when-i-get-up-tabs-1025130', 'tab'],
  ['Pearl Jam', 'Just Breathe (ver 2)', 'pearl-jam/just-breathe-chords-875531', 'chords'],
  ['Pearl Jam', 'Just Breathe', 'pearl-jam/just-breathe-tabs-875332', 'tab'],
  ['The Beatles', 'Yesterday (ver 4)', 'the-beatles/yesterday-tabs-46978', 'tab'],
  ['Josh Ritter', 'Naked As A Window', 'josh-ritter/naked-as-a-window-chords-666209', 'chords'],
  ['John Prine', 'Paradise (ver 3)', 'john-prine/paradise-chords-1051304', 'chords'],
  ['Bruce Springsteen', 'Dancing In The Dark (ver 5)', 'bruce-springsteen/dancing-in-the-dark-chords-1087212', 'chords'],
  ['Ed Sheeran', 'Perfect', 'ed-sheeran/perfect-chords-1956589', 'chords'],
  ['Bob Dylan', 'Dont Think Twice Its All Right (ver 2)', 'bob-dylan/dont-think-twice-its-all-right-chords-178850', 'chords'],
  ['John Prine', 'Sam Stone (ver 3)', 'john-prine/sam-stone-chords-1052027', 'chords'],
  ['John Prine', 'Speed Of The Sound Of Loneliness (ver 2)', 'john-prine/speed-of-the-sound-of-loneliness-chords-1723392', 'chords'],
  ['John Prine', 'Bruised Orange', 'john-prine/bruised-orange-chords-79960', 'chords'],
  ['Simon & Garfunkel', 'Kathys Song', 'simon-garfunkel/kathys-song-chords-1091921', 'chords'],
  ['Big Thief', 'Masterpiece', 'big-thief/masterpiece-chords-1853337', 'chords'],
  ['Big Thief', 'Mary', 'big-thief/mary-chords-2070761', 'chords'],
  ['The Beatles', 'Ive Just Seen A Face (ver 4)', 'the-beatles/ive-just-seen-a-face-chords-1061795', 'chords'],
  ['The Beatles', 'When Im Sixty Four (ver 2)', 'the-beatles/when-im-sixty-four-chords-742035', 'chords'],
  ['Misc Soundtrack', 'A Star Is Born - Shallow', 'misc-soundtrack/a-star-is-born-shallow-chords-2480119', 'chords'],
  ['Tom Petty and The Heartbreakers', 'Walls Circus', 'tom-petty-and-the-heartbreakers/walls-circus-chords-437320', 'chords'],
  ['The National', 'I Need My Girl', 'the-national/i-need-my-girl-chords-1197424', 'chords'],
  ['Bruce Springsteen', 'The Rising (ver 3)', 'bruce-springsteen/the-rising-chords-1088613', 'chords'],
  ['Doug Paisley', 'Waiting', 'doug-paisley/waiting-chords-2555709', 'chords'],
  ['Bob Dylan', 'Dont Think Twice Its All Right', 'bob-dylan/dont-think-twice-its-all-right-official-2089509', 'official'],
  ['Wilco', 'Bob Dylans Beard', 'wilco/bob-dylans-beard-chords-445834', 'chords'],
  ['Wreckless Eric', 'Whole Wide World', 'wreckless-eric/whole-wide-world-chords-1664595', 'chords'],
  ['Jeff Buckley', 'Hallelujah (ver 2)', 'jeff-buckley/hallelujah-chords-198052', 'chords'],
  ['Courtney Barnett', 'Depreston', 'courtney-barnett/depreston-chords-1516448', 'chords'],
  ['Wilco', 'Jesus Etc (ver 4)', 'wilco/jesus-etc-chords-581246', 'chords'],
  ['Wilco', 'On And On And On', 'wilco/on-and-on-and-on-chords-820662', 'chords'],
  ['Phosphorescent', 'New Birth In New England (ver 2)', 'phosphorescent/new-birth-in-new-england-chords-2558985', 'chords'],
  ['Bob Dylan', 'Emotionally Yours', 'bob-dylan/emotionally-yours-chords-14862', 'chords'],
  ['Jeff Tweedy', 'I Know What Its Like', 'jeff-tweedy/i-know-what-its-like-chords-2532672', 'chords'],
  ['Misc Children', 'Down By The Station', 'misc-children/down-by-the-station-chords-1886010', 'chords'],
  ['Wilco', 'Kamera', 'wilco/kamera-chords-877477', 'chords'],
  ['Jeff Tweedy', 'Warm When The Sun Has Died', 'jeff-tweedy/warm-when-the-sun-has-died-chords-2537991', 'chords'],
  ['Travis', 'Why Does It Always Rain On Me (ver 5)', 'travis/why-does-it-always-rain-on-me-chords-917471', 'chords'],
  ['John Prine', 'How Lucky', 'john-prine/how-lucky-chords-772846', 'chords'],
  ['John Denver', 'Take Me Home Country Roads (ver 5)', 'john-denver/take-me-home-country-roads-chords-1101747', 'chords'],
  ['R.E.M.', 'Losing My Religion (ver 2)', 'r-e-m-/losing-my-religion-chords-114345', 'chords'],
  ['Jeff Tweedy', 'Dont Forget', 'jeff-tweedy/dont-forget-chords-2537964', 'chords'],
  ['Josh Ritter', 'Henrietta Indiana (ver 2)', 'josh-ritter/henrietta-indiana-chords-1774207', 'chords'],
  ['Bob Dylan', 'Must Be Santa', 'bob-dylan/must-be-santa-chords-1445248', 'chords'],
  ['Misc Christmas', 'Jingle Bells', 'misc-christmas/jingle-bells-chords-273336', 'chords'],
  ['Misc Christmas', 'Santa Claus Is Coming To Town', 'misc-christmas/santa-claus-is-coming-to-town-chords-448824', 'chords'],
  ['Wilco', 'Via Chicago (ver 2)', 'wilco/via-chicago-chords-1852154', 'chords'],
  ['Misc Children', 'Old Macdonald Had A Farm', 'misc-children/old-macdonald-had-a-farm-chords-1716414', 'chords'],
  ['Radiohead', 'True Love Waits (ver 2)', 'radiohead/true-love-waits-chords-1846926', 'chords'],
  ['Phoebe Bridgers', 'Funeral', 'phoebe-bridgers/funeral-chords-2150411', 'chords'],
  ['Josh Ritter', 'Good Man (ver 2)', 'josh-ritter/good-man-chords-797419', 'chords'],
  ['Josh Ritter', 'Thin Blue Flame', 'josh-ritter/thin-blue-flame-chords-568743', 'chords'],
  ['Bruce Springsteen', 'Im On Fire (ver 3)', 'bruce-springsteen/im-on-fire-chords-1047368', 'chords'],
  ['Ron Hynes', 'Sonnys Dream (ver 2)', 'ron-hynes/sonnys-dream-chords-1684265', 'chords'],
  ['Buddy Wasisname and the Other Fellers', 'Saltwater Joys', 'buddy-wasisname-and-the-other-fellers/saltwater-joys-chords-356356', 'chords'],
  ['Middle Tickle', 'Joe Batts Arm Longliners', 'middle-tickle/joe-batts-arm-longliners-chords-1780344', 'chords'],
  ['George Harrison', 'My Sweet Lord', 'george-harrison/my-sweet-lord-chords-106200', 'chords'],
  ['Radiohead', 'Karma Police (ver 2)', 'radiohead/karma-police-chords-103398', 'chords'],
  ['Bruce Springsteen', 'Human Touch (ver 2)', 'bruce-springsteen/human-touch-chords-344739', 'chords'],
  ['Bob Dylan', 'Thirsty Boots', 'bob-dylan/thirsty-boots-chords-1849801', 'chords'],
  ['Sixpence None The Richer', 'Kiss Me (ver 2)', 'sixpence-none-the-richer/kiss-me-chords-2707', 'chords'],
  ['Travis', 'The Only Thing', 'travis/the-only-thing-chords-3332738', 'chords'],
  ['Sharon Van Etten', 'Like I Used To', 'sharon-van-etten/like-i-used-to-chords-3716609', 'chords'],
  ['Mark Knopfler', 'All The Roadrunning', 'mark-knopfler/all-the-roadrunning-chords-995393', 'chords'],
  ['Adrianne Lenker', 'Dragon Eyes', 'adrianne-lenker/dragon-eyes-chords-3358985', 'chords'],
  ['Bob Dylan', 'Its All Over Now Baby Blue', 'bob-dylan/its-all-over-now-baby-blue-chords-14884', 'chords'],
  ['Ben E. King', 'Stand By Me (ver 7)', 'ben-e-king/stand-by-me-chords-1724608', 'chords'],
  ['Gillian Welch', 'Everything Is Free (ver 2)', 'gillian-welch/everything-is-free-chords-1117815', 'chords'],
  ['The Weakerthans', 'One Great City', 'the-weakerthans/one-great-city-chords-2232017', 'chords'],
  ['The National', 'Demons', 'the-national/demons-chords-1243744', 'chords'],
  ['The National', 'I Should Live In Salt (ver 2)', 'the-national/i-should-live-in-salt-chords-1420785', 'chords'],
  ['The National', 'Dont Swallow The Cap', 'the-national/dont-swallow-the-cap-chords-1246343', 'chords'],
  ['The National', 'Fireproof', 'the-national/fireproof-chords-1247359', 'chords'],
  ['The Clancy Brothers and Tommy Makem', 'The Butcher Boy', 'the-clancy-brothers-and-tommy-makem/the-butcher-boy-chords-2242433', 'chords'],
  ['Bob Dylan', 'Silver Dagger', 'bob-dylan/silver-dagger-chords-740557', 'chords'],
  ['Shanneyganock', 'Grey Foggy Day', 'shanneyganock/grey-foggy-day-chords-1675790', 'chords'],
  ['Daniel Johnston', 'True Love Will Find You In The End', 'daniel-johnston/true-love-will-find-you-in-the-end-chords-438749', 'chords'],
  ['Phoebe Bridgers', 'If We Make It Through December', 'phoebe-bridgers/if-we-make-it-through-december-chords-3437717', 'chords'],
  ['Phoebe Bridgers', 'That Funny Feeling', 'phoebe-bridgers/that-funny-feeling-chords-3896612', 'chords'],
  ['Bo Burnham', 'That Funny Feeling', 'bo-burnham/that-funny-feeling-chords-3731324', 'chords'],
  ['Aldous Harding', 'Treasure', 'aldous-harding/treasure-chords-2718408', 'chords'],
  ['Aldous Harding', 'Horizon', 'aldous-harding/horizon-chords-1964107', 'chords'],
  ['Big Thief', 'Change', 'big-thief/change-chords-3894680', 'chords'],
  ['Leonard Cohen', 'Bird On The Wire', 'leonard-cohen/bird-on-the-wire-chords-64967', 'chords'],
  ['Courtney Barnett', 'Oh The Night', 'courtney-barnett/oh-the-night-chords-3988330', 'chords'],
  ['The Lumineers', 'Cleopatra', 'the-lumineers/cleopatra-chords-1829195', 'chords'],
  ['John Prine', 'Wish You All The Best', 'john-prine/wish-you-all-the-best-chords-2460586', 'chords'],
  ['Josh Ritter', 'Change Of Time', 'josh-ritter/change-of-time-chords-2838476', 'chords'],
  ['Josh Ritter', 'Blazing Highway Home', 'josh-ritter/blazing-highway-home-chords-2680170', 'chords'],
  ['Sharon Van Etten', 'One Day', 'sharon-van-etten/one-day-chords-1010913', 'chords'],
  ['Alvvays', 'Bored In Bristol', 'alvvays/bored-in-bristol-chords-4377395', 'chords'],
  ['Alvvays', 'Forget About Life', 'alvvays/forget-about-life-chords-2149961', 'chords'],
  ['Alvvays', 'Archie Marry Me', 'alvvays/archie-marry-me-chords-1505360', 'chords'],
  ['Alvvays', 'Dreams Tonite', 'alvvays/dreams-tonite-chords-1974423', 'chords'],
  ['Alvvays', 'Not My Baby', 'alvvays/not-my-baby-chords-1948397', 'chords'],
  ['Alvvays', 'Velveteen', 'alvvays/velveteen-chords-4377341', 'chords'],
  ['Alvvays', 'Saved By A Waif', 'alvvays/saved-by-a-waif-chords-2084087', 'chords'],
  ['John Prine', 'Knockin On Your Screen Door', 'john-prine/knockin-on-your-screen-door-chords-2330565', 'chords'],
  ['Josh Ritter', 'Horse No Rider', 'josh-ritter/horse-no-rider-chords-4662977', 'chords'],
  ['Misc Cartoons', 'Encanto - Dos Oruguitas', 'misc-cartoons/encanto-dos-oruguitas-chords-3956728', 'chords'],
  ['Phoebe Bridgers', 'I Know The End', 'phoebe-bridgers/i-know-the-end-chords-3100499', 'chords'],
  ['Bob Dylan', 'Annies Going To Sing Her Song', 'bob-dylan/annies-going-to-sing-her-song-chords-1749646', 'chords'],
  ['boygenius', 'Emily Im Sorry', 'boygenius/emily-im-sorry-chords-4608749', 'chords'],
  ['Lana Del Rey', 'If You Lie Down With Me', 'lana-del-rey/if-you-lie-down-with-me-chords-3912344', 'chords'],
  ['Lana Del Rey', 'Chemtrails Over The Country Club', 'lana-del-rey/chemtrails-over-the-country-club-chords-3509777', 'chords'],
  ['Warren Zevon', 'Keep Me In Your Heart For A While', 'warren-zevon/keep-me-in-your-heart-for-a-while-chords-2271455', 'chords'],
  ['Josh Ritter', 'Kathleen (ver 2)', 'josh-ritter/kathleen-chords-509420', 'chords'],
  ['Adrianne Lenker', 'Jonathan (ver 2)', 'adrianne-lenker/jonathan-chords-3038766', 'chords'],
  ['Adrianne Lenker', 'Indiana', 'adrianne-lenker/indiana-tabs-1929271', 'tab'],
  ['Adrianne Lenker', 'Sadness As A Gift', 'adrianne-lenker/sadness-as-a-gift-chords-5108878', 'chords'],
  ['BoyWithUke', 'Prairies', 'boywithuke/prairies-chords-4183723', 'chords'],
  ['Fleet Foxes', 'Im Not My Season (ver 2)', 'fleet-foxes/im-not-my-season-chords-3347642', 'chords'],
  ['Josh Ritter', 'When Will I Be Changed', 'josh-ritter/when-will-i-be-changed-chords-1447930', 'chords'],
  ['John Prine', 'I Have Met My Love Today', 'john-prine/i-have-met-my-love-today-chords-2366159', 'chords'],
  ['Misc Soundtrack', 'A Star Is Born - Always Remember Us This Way', 'misc-soundtrack/a-star-is-born-always-remember-us-this-way-chords-2484211', 'chords'],
  ['Misc Soundtrack', 'Barbie - What Was I Made For', 'misc-soundtrack/barbie-what-was-i-made-for-chords-4871180', 'chords'],
  ['Chappell Roan', 'Good Luck Babe', 'chappell-roan/good-luck-babe-chords-5191149', 'chords'],
  ['Alvvays', 'Party Police', 'alvvays/party-police-chords-1696765', 'chords'],
  ['The Magnetic Fields', 'Smoke And Mirrors', 'the-magnetic-fields/smoke-and-mirrors-chords-1906125', 'chords'],
  ['Steve Fisher', 'Anything', 'steve-fisher/anything-chords-4962187', 'chords'],
  ['Kate Bush', 'This Womans Work (ver 3)', 'kate-bush/this-womans-work-chords-3330971', 'chords'],
  ['The Tragically Hip', 'Get Back Again (ver 2)', 'the-tragically-hip/get-back-again-chords-2275899', 'chords'],
  ['Kacey Musgraves', 'The Architect', 'kacey-musgraves/the-architect-chords-5185071', 'chords'],
  ['Kacey Musgraves', 'Deeper Well', 'kacey-musgraves/deeper-well-chords-5139562', 'chords'],
  ['Kacey Musgraves', 'Nothing To Be Scared Of', 'kacey-musgraves/nothing-to-be-scared-of-chords-5185548', 'chords'],
  ['Big Thief', 'Dried Roses', 'big-thief/dried-roses-chords-4029652', 'chords'],
  ['The Smashing Pumpkins', '1979 (ver 4)', 'the-smashing-pumpkins/1979-guitar-pro-419873', 'guitar-pro'],
  ['Leonard Cohen', 'Famous Blue Raincoat', 'leonard-cohen/famous-blue-raincoat-chords-64974', 'chords'],
  ['Travis', 'Side', 'travis/side-chords-2468902', 'chords'],
  ['Travis', 'More Than Us', 'travis/more-than-us-chords-1312', 'chords'],
  ['Radiohead', 'Let Down', 'radiohead/let-down-chords-596727', 'chords'],
  ['Tom Petty', 'Time To Move On', 'tom-petty/time-to-move-on-chords-5668', 'chords'],
  ['Carly Rae Jepsen', 'Bends', 'carly-rae-jepsen/bends-chords-4393289', 'chords'],
  ['Weezer', 'Island In The Sun', 'weezer/island-in-the-sun-chords-852868', 'chords'],
  ['Weezer', 'Butterfly (ver 3)', 'weezer/butterfly-chords-1491934', 'chords'],
  ['Big Thief', 'Paul', 'big-thief/paul-chords-1869562', 'chords'],
  ['Carly Rae Jepsen', 'Comeback', 'carly-rae-jepsen/comeback-chords-3164168', 'chords'],
  ['Bob Dylan', 'Is Your Love In Vain', 'bob-dylan/is-your-love-in-vain-chords-927759', 'chords'],
  ['Bob Dylan', 'Señor Tales Of Yankee Power', '14925', 'chords'],
  ['Carly Rae Jepsen', 'Favourite Colour (ver 2)', 'carly-rae-jepsen/favourite-colour-chords-2684181', 'chords'],
  ['Carly Rae Jepsen', 'Cut To The Feeling (ver 2)', 'carly-rae-jepsen/cut-to-the-feeling-chords-2007431', 'chords'],
  ['Carly Rae Jepsen', 'Fever', 'carly-rae-jepsen/fever-chords-1871785', 'chords'],
  ['Carly Rae Jepsen', 'More', 'carly-rae-jepsen/more-chords-5917724', 'chords'],
  ['Carly Rae Jepsen', 'The Loneliest Time', 'carly-rae-jepsen/the-loneliest-time-chords-4375631', 'chords'],
  ['Neil Young', 'Only Love Can Break Your Heart (ver 9)', 'neil-young/only-love-can-break-your-heart-chords-1742296', 'chords'],
  ['Neil Young', 'Thrasher', 'neil-young/thrasher-chords-470221', 'chords'],
  ['Carly Rae Jepsen', 'When I Needed You', 'carly-rae-jepsen/when-i-needed-you-chords-1872059', 'chords'],
  ['Carly Rae Jepsen', 'Too Much', 'carly-rae-jepsen/too-much-chords-2689920', 'chords'],
  ['Bob Dylan', 'Mississippi (ver 2)', 'bob-dylan/mississippi-chords-1752304', 'chords'],
  ['Big Thief', 'Born For Loving You', 'big-thief/born-for-loving-you-chords-4728164', 'chords'],
  ['Big Thief', 'How Could I Have Known', 'big-thief/how-could-i-have-known-chords-5937902', 'chords'],
  ['Wilco', 'How To Fight Loneliness (ver 2)', 'wilco/how-to-fight-loneliness-chords-1752509', 'chords'],
  ['Wilco', 'How To Fight Loneliness', 'wilco/how-to-fight-loneliness-official-4259071', 'official'],
  ['Merle Haggard', 'If We Make It Through December (ver 2)', 'merle-haggard/if-we-make-it-through-december-chords-1115977', 'chords'],
  ['Wilco', 'I Am Trying To Break Your Heart (ver 2)', 'wilco/i-am-trying-to-break-your-heart-chords-1166368', 'chords'],
  ['Wilco', 'Please Be Patient With Me (ver 3)', 'wilco/please-be-patient-with-me-tabs-802585', 'tab'],
  ['Josh Ritter', 'In Your Arms Awhile', 'josh-ritter/in-your-arms-awhile-chords-1231708', 'chords'],
  ['Angel Olsen', 'Big Time', 'angel-olsen/big-time-chords-4170475', 'chords'],
  ['Leonard Cohen', 'Hallelujah', 'leonard-cohen/hallelujah-chords-64977', 'chords'],
  ['Andy Shauf', 'Try Again', 'andy-shauf/try-again-chords-2893472', 'chords'],
  ['Leonard Cohen', 'Alexandra Leaving (ver 4)', 'leonard-cohen/alexandra-leaving-chords-2008425', 'chords'],
  ['Kathleen Edwards', 'Little Red Ranger', 'kathleen-edwards/little-red-ranger-chords-5898176', 'chords'],
  ['Bob Dylan', 'Every Grain Of Sand (ver 3)', 'bob-dylan/every-grain-of-sand-chords-1135862', 'chords'],
  ['Adrianne Lenker', 'Free Treasure', 'adrianne-lenker/free-treasure-chords-5192019', 'chords'],
  ['Angel Olsen', 'All The Flowers', 'angel-olsen/all-the-flowers-chords-4218127', 'chords'],
];

export function favoriteSeedSongs(now: number): Song[] {
  return ROWS.map(([artist, title, path, type], i) => ({
    id: `fav-${i}`,
    title,
    artist,
    key: '',
    capo: 0,
    body: '',
    sourceUrl: UG_BASE + path,
    tags: ['favorites', type],
    createdAt: now + i, // preserve order via creation time
    updatedAt: now + i,
  }));
}
